version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: xuitter
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xuitter
      MYSQL_USER: xuitter
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
